<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="10" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="16791" started-at="2022-05-14T23:31:08 IST" finished-at="2022-05-14T23:31:25 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="16791" started-at="2022-05-14T23:31:08 IST" finished-at="2022-05-14T23:31:25 IST">
      <class name="org.testing.TestScripts.TC3_GetAllRequest">
        <test-method status="PASS" signature="testcase3()[pri:0, instance:org.testing.TestScripts.TC3_GetAllRequest@4923ab24]" name="testcase3" duration-ms="265" started-at="2022-05-14T23:31:12 IST" finished-at="2022-05-14T23:31:12 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase3 -->
      </class> <!-- org.testing.TestScripts.TC3_GetAllRequest -->
      <class name="org.testing.TestScripts.TC10_DeleteEmployeeRequest">
        <test-method status="PASS" signature="testcase10()[pri:0, instance:org.testing.TestScripts.TC10_DeleteEmployeeRequest@371a67ec]" name="testcase10" duration-ms="2444" started-at="2022-05-14T23:31:23 IST" finished-at="2022-05-14T23:31:25 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase10 -->
      </class> <!-- org.testing.TestScripts.TC10_DeleteEmployeeRequest -->
      <class name="org.testing.TestScripts.TC4_PutRequest">
        <test-method status="PASS" signature="testcase4()[pri:0, instance:org.testing.TestScripts.TC4_PutRequest@44c8afef]" name="testcase4" duration-ms="75" started-at="2022-05-14T23:31:12 IST" finished-at="2022-05-14T23:31:12 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase4 -->
      </class> <!-- org.testing.TestScripts.TC4_PutRequest -->
      <class name="org.testing.TestScripts.TC8_GetAllEmployeeRequest">
        <test-method status="FAIL" signature="testcase8()[pri:0, instance:org.testing.TestScripts.TC8_GetAllEmployeeRequest@13c27452]" name="testcase8" duration-ms="2311" started-at="2022-05-14T23:31:17 IST" finished-at="2022-05-14T23:31:19 IST">
          <exception class="io.restassured.path.json.exception.JsonPathException">
            <message>
              <![CDATA[Failed to parse the JSON document]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at org.testing.utilities.ParsingJsonUsingJsonPath.parseJsonPath(ParsingJsonUsingJsonPath.java:9)
at org.testing.responseValidation.ResponseValidate.DataValidate(ResponseValidate.java:26)
at org.testing.TestScripts.TC8_GetAllEmployeeRequest.testcase8(TC8_GetAllEmployeeRequest.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 34 more
]]>
            </full-stacktrace>
          </exception> <!-- io.restassured.path.json.exception.JsonPathException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase8 -->
      </class> <!-- org.testing.TestScripts.TC8_GetAllEmployeeRequest -->
      <class name="org.testing.TestScripts.TC7_GetEmployeeRequest">
        <test-method status="FAIL" signature="testcase7()[pri:0, instance:org.testing.TestScripts.TC7_GetEmployeeRequest@12f41634]" name="testcase7" duration-ms="2448" started-at="2022-05-14T23:31:15 IST" finished-at="2022-05-14T23:31:17 IST">
          <exception class="io.restassured.path.json.exception.JsonPathException">
            <message>
              <![CDATA[Failed to parse the JSON document]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at org.testing.utilities.ParsingJsonUsingJsonPath.parseJsonPath(ParsingJsonUsingJsonPath.java:9)
at org.testing.responseValidation.ResponseValidate.DataValidate(ResponseValidate.java:26)
at org.testing.TestScripts.TC7_GetEmployeeRequest.testcase7(TC7_GetEmployeeRequest.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 34 more
]]>
            </full-stacktrace>
          </exception> <!-- io.restassured.path.json.exception.JsonPathException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase7 -->
      </class> <!-- org.testing.TestScripts.TC7_GetEmployeeRequest -->
      <class name="org.testing.TestScripts.TC9_PutEmployeeRequest">
        <test-method status="FAIL" signature="testcase9()[pri:0, instance:org.testing.TestScripts.TC9_PutEmployeeRequest@262b2c86]" name="testcase9" duration-ms="3415" started-at="2022-05-14T23:31:19 IST" finished-at="2022-05-14T23:31:23 IST">
          <exception class="io.restassured.path.json.exception.JsonPathException">
            <message>
              <![CDATA[Failed to parse the JSON document]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at org.testing.utilities.ParsingJsonUsingJsonPath.parseJsonPath(ParsingJsonUsingJsonPath.java:9)
at org.testing.responseValidation.ResponseValidate.DataValidate(ResponseValidate.java:26)
at org.testing.TestScripts.TC9_PutEmployeeRequest.testcase9(TC9_PutEmployeeRequest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 34 more
]]>
            </full-stacktrace>
          </exception> <!-- io.restassured.path.json.exception.JsonPathException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase9 -->
      </class> <!-- org.testing.TestScripts.TC9_PutEmployeeRequest -->
      <class name="org.testing.TestScripts.TC1_PostRequest">
        <test-method status="PASS" signature="testcase1()[pri:0, instance:org.testing.TestScripts.TC1_PostRequest@60285225]" name="testcase1" duration-ms="2251" started-at="2022-05-14T23:31:09 IST" finished-at="2022-05-14T23:31:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
      </class> <!-- org.testing.TestScripts.TC1_PostRequest -->
      <class name="org.testing.TestScripts.TC5_DeleteRequest">
        <test-method status="PASS" signature="testcase5()[pri:0, instance:org.testing.TestScripts.TC5_DeleteRequest@7b69c6ba]" name="testcase5" duration-ms="45" started-at="2022-05-14T23:31:12 IST" finished-at="2022-05-14T23:31:12 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase5 -->
      </class> <!-- org.testing.TestScripts.TC5_DeleteRequest -->
      <class name="org.testing.TestScripts.TC2_GetRequest">
        <test-method status="PASS" signature="testcase2()[pri:0, instance:org.testing.TestScripts.TC2_GetRequest@670b40af]" name="testcase2" duration-ms="1015" started-at="2022-05-14T23:31:11 IST" finished-at="2022-05-14T23:31:12 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase2 -->
      </class> <!-- org.testing.TestScripts.TC2_GetRequest -->
      <class name="org.testing.TestScripts.TC6_PostRequestEmployee">
        <test-method status="PASS" signature="testcase6()[pri:0, instance:org.testing.TestScripts.TC6_PostRequestEmployee@46daef40]" name="testcase6" duration-ms="2400" started-at="2022-05-14T23:31:12 IST" finished-at="2022-05-14T23:31:15 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase6 -->
      </class> <!-- org.testing.TestScripts.TC6_PostRequestEmployee -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
